spring:
  datasource:
    url: jdbc:mysql://localhost/training_db
    username: root
    password: '#Perigoso_1097'

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
